name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docs/**'
      - '!.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-next-${{ github.sha }} # 常に新しいキャッシュを作成
          restore-keys: |
            ${{ runner.os }}-next-
      - name: Install dependencies
        run: |
          npm ci
      - name: Run build
        run: npm run build:dev
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
